site_name: Open-Channel Solid State Drives
theme: readthedocs

pages:
 - Introduction: index.md
 - User Documentation:
     - 'Getting Started': gettingstarted.md
     - 'Commands': commands.md
 - Developer Documentation:
     - 'Specification': specification.md
     - 'Source files': source.md
     - 'Modules': modules.md
