site_name: Open-Channel Solid State Drives
theme: readthedocs
repo_url: https://github.com/OpenChannelSSD/Documentation
google_analytics: ['UA-57193430-2', 'openchannelssd.readthedocs.org']
pages:
 - Introduction: index.md
 - User Documentation:
     - 'Getting Started': gettingstarted.md
     - 'Command Line': commands.md
     - 'Debugging Interface' : debug.md
 - Developer Documentation:
     - 'Projects': projects.md
     - 'Specification': specification.md
     - 'Source files': source.md
     - 'Kernel API': api.md
